# Generated by Django 3.1.2 on 2021-04-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_player_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
    ]
