# Generated by Django 3.1.2 on 2021-04-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_question_no',
            field=models.IntegerField(default=1),
        ),
    ]
