# Generated by Django 3.1.2 on 2021-04-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_auto_20210423_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_question_no',
            field=models.IntegerField(default=0),
        ),
    ]
