# Generated by Django 3.1.2 on 2021-04-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_auto_20210423_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='quizapp/media'),
        ),
    ]
