# Generated by Django 3.1.2 on 2021-04-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_player_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='media',
        ),
        migrations.AddField(
            model_name='questions',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='quizapp/media'),
        ),
    ]
