# Generated by Django 3.1.2 on 2021-04-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_auto_20210423_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='media',
        ),
        migrations.AddField(
            model_name='questions',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='quizapp/audio'),
        ),
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='quizapp/image'),
        ),
    ]
